Fix error logic

diff --git a/.github/workflows/update_eic_lxr_repo_list.yml b/.github/workflows/update_eic_lxr_repo_list.yml
--- a/.github/workflows/update_eic_lxr_repo_list.yml
+++ b/.github/workflows/update_eic_lxr_repo_list.yml
@@ -38,6 +38,16 @@ jobs:
           while true; do
             response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$API_URL?page=$page&per_page=100")
 
+            # Check if the response is not an array
+            if ! echo "$response" | jq -e 'type != "array"' > /dev/null; then
+              # Check if the response contains an error message field
+              if echo "$response" | jq -e 'has("message")' > /dev/null; then
+                error_message=$(echo "$response" | jq -r '.message')
+                echo "Error: $error_message"
+                break
+              fi
+            fi
+            
             # Check if there are no more repositories
             if [[ "$(echo "$response" | jq length)" -eq 0 ]]; then
               break
@@ -48,10 +58,14 @@ jobs:
               commits_url="https://api.github.com/repos/$ORG_NAME/$repo_name/commits?per_page=1"
               commit_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "$commits_url")
 
-              # Check if there are no commits
-              if [[ "$(echo "$commit_response" | jq length)" -eq 0 ]]; then
-                echo "No commits found for repository: $repo_name"
-                break
+              # Check if the response is not an array
+              if ! echo "$commit_response" | jq -e 'type != "array"' > /dev/null; then
+                # Check if the response contains an error message field
+                if echo "$commit_response" | jq -e 'has("message")' > /dev/null; then
+                  error_message=$(echo "$response" | jq -r '.message')
+                  echo "Error: $error_message"
+                  continue
+                fi
               fi
 
               echo $commit_response | jq .
